name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.53.200.100 << 'EOF'
            cd ~/my-backend-app
            docker-compose down
            docker pull medomane/my-backend-app:latest
            docker-compose up -d
          EOF
